### ISSUE TITLE
Bug: Crashes if you press a key while game loops is running

### ISSUE THREAD

**Issue by MSaIim** [arthurquinn/solitaire#18]
If you press a key when game loop is running, the engine will crash with an AssertionException (something to do with the Json).

**Comment by arthurquinn** [comment]
That's because the engine isn't designed for keyboard input, it's designed for JSON input from gui. My suggestion is if you want to test the engine, write up a quick python script to launch an engine and take your keyboard input and turn it into JSON and send it to the engine. I'm combination with a logger you can make sure the engine is working properly.
